remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: "Abhishek Bharti"
description: "Senior Data Scientist Portfolio"
email: abhishek@example.com
baseurl: ""
url: "https://yourusername.github.io"
theme: minima

header_pages:
  - index.md
  - about.md
  - blog.md
